// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Diagnostics;

namespace LiRoInspect.iOS
{
	public partial class ImagePeviewViewController : UIViewController
	{
		public UIImageView previewImage = new UIImageView ();
		public ImagePeviewViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            try
            {
                base.ViewDidLoad();
                btnClose.TouchUpInside += BtnClose_TouchUpInside;
                imgViewPreview.Image = previewImage.Image;
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Exception Occured in viewDidLaod method due to " + ex.Message);
            }
        }

		void BtnClose_TouchUpInside (object sender, EventArgs e)
		{
			this.DismissViewControllerAsync (false);
		}
	}
}
