// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LiRoInspect.iOS
{
	public partial class OptionsCell : UITableViewCell
	{
		public OptionsCell (IntPtr handle) : base (handle)
		{
		}
	}
}
