// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LiRoInspect.iOS
{
	public partial class UIFailViewController : UIViewController
	{
		public UIFailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
